[package]
name = "fluffy-birb"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
iced_futures = "0.13.1"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
futures = "0.3"
async-std = "1.12"
